#! /bin/bash

backup="/var/lib/mercurial-server/bin/get-database-content"
backup="/home/git/bin/get-database-content"

$backup hybrida_dev structure > hybrida_dev.structure.sql
$backup hybrida	    structure > hybrida.structure.sql

vimdiff hybrida_dev.structure.sql hybrida.structure.sql

rm hybrida_dev.structure.sql hybrida.structure.sql

