#! /usr/bin/env python

import os, os.path
import sqlite3
import hashlib
import re
import argparse
from pprint import pprint

"""
Fjerner alle sql-data som kan være sensitive (epost, tlf o.s.v.)
"""

class Store:

	def __init__(self, name):
		self.con = sqlite3.connect(name)
		self.cursor = self.con.cursor()


	def setup_db(self):
		sql = "create table store (key varchar(255) primary key, value TEXT)"
		self.cursor.execute(sql)


	def get(self, key):
		sql = "select value from store where key = ?"
		ans = self.cursor.execute(sql, (key,))
		value = ans.fetchone()
		if value:
			return value[0]
		else:
			return None

	def push(self, key, value):
		sql = "insert into store VALUES (?, ?)"
		self.cursor.execute(sql, (key, value))

	def commit(self):
		self.con.commit()

	def reset(self):
		self.drop()
		self.setup_db()

	def drop(self):
		sql = "drop table store"
		self.cursor.execute(sql)

	def count(self):
		sql = "select count(key) from store"
		res = self.cursor.execute(sql)
		value = res.fetchone()
		return value[0]

	def list(self):
		sql = "select key from store"
		res = self.cursor.execute(sql)
		values = res.fetchall()
		return [v[0] for v in values]




class OpensourceifySqldata:

	def __init__(self):
		self.files = self.get_files(".")
		self.db_files = ["backup.sql", "db/backup.sql"]
		self.store = Store("/var/www/store.db")

	def get_files(self, path):
		files = os.listdir(path)
		return [file for file in files if os.path.isfile(file)]

	def get_file_lines(self, path):
		with open(path, "rb") as file:
			return [x.rstrip().decode() for x in file]



	def write_file_contents(self, path, content):
		with open(path, "w") as file:
			file.write(content)


	def work(self):
		files = ["backup.sql", "db/backup.sql", "db/data.sql", "db/db.sql"]
		found = []

		for file in files:
			if os.path.isfile(file):
				print(file, end=": ")
				self.rewrite_and_hash(file)
				found.append(file)

		if not found:
			print("Fant ingen DB-filer")
		elif len(found) > 1:
			print("Fant flere db-filer:", found)



	def rewrite_and_hash(self, filepath):
		old_lines = self.get_file_lines(filepath)
		old_content = "\n".join(old_lines) + "\n"
		hash = hashlib.sha224(old_content.encode()).hexdigest()

		prev = self.store.get(hash)

		if prev:
			print("Store:", hash)
			self.write_file_contents(filepath, prev)
			return

		new_lines = self.rewrite(old_lines)

		self.write_diff(hash, old_lines, new_lines)

		new_content = "\n".join(new_lines) + "\n"

		self.store.push(hash, new_content)
		self.write_file_contents(filepath, new_content)
		self.store.commit()

	def rewrite(self, lines):
		line_len_begin = len(lines)
		tables = ["user", "user_new", "user_info", "hyb_user", "hyb_user_info", "hyb_user_new"]
		for table in tables:
			lines = self.rewrite_table(table, lines)
		line_len_end = len(lines)
		print("before:", line_len_begin, "after:", line_len_end)
		return lines

	def rewrite_table(self, table, lines):
		matches = []
		done = False
		new_lines = []
		insert_prog = re.compile(r"^INSERT INTO \`{}\`".format(table))
		kept_users_prog = re.compile(r"\((381|466)")
		kept_users = []


		for i, line in enumerate(lines):
			if insert_prog.match(line):
				if matches:
					continue
				else:
					matches.append(i)
					new_lines.append(line)
			elif matches and not done and kept_users_prog.match(line):
				the_line = line[:-1].replace("sighol@gmail.com", "not_real@gmail.com")
				kept_users.append(the_line)
			elif matches and line.strip() == "" and not done:
				done = True
				users = ",\n".join(kept_users) + ";"
				# print(table, i, [u[0:30] for u in kept_users])
				new_lines.append(users)
				new_lines.append(line)
			elif matches and not done:
				pass
			else:
				new_lines.append(line)

		return new_lines

	def write_diff(self, hash, old_lines, new_lines):
		# Skal se hvilke som som er tatt ut
		new_set = set(new_lines)
		not_in_new = []
		old_set = set(old_lines)
		not_in_old = []

		for line in old_lines:
			if line not in new_set:
				not_in_new.append(line)

		for line in new_lines:
			if line not in old_set:
				not_in_old.append(line)

		filepath = "/var/www/diffs/"
		os.system("mkdir -p " + filepath)

		with open(filepath + hash, 'w') as file:
			for line in not_in_new:
				file.write("- " + line + "\n")
			for line in not_in_old:
				file.write("+ " + line + "\n")


if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument("--reset", action="store_true")
	parser.add_argument("--count", action="store_true")
	parser.add_argument("--list", action="store_true")
	args = parser.parse_args()

	o = OpensourceifySqldata()

	if args.reset:
		o.store.reset()
	elif args.count:
		count = o.store.count()
		print(count)
	elif args.list:
		print(o.store.list())
	else:
		o.work()
