#! /bin/bash

prod="/var/www/hybrida-prod"

cd $prod

git checkout production

git pull origin master

git merge master



echo "oppdaterer css"
rm -f css/min.css
cd css
cat * > min.css

cd $prod

echo "Oppdatering er ferdig"
